---
- name: Deploy app on production server
  hosts: all
  become: yes
  user: root

  tasks:
  - name: Rename The Directory
    command: chdir=/mnt/ rm -rf *
    
  - name: copy app to remote server
    copy:
      src: ../../IAC
      dest: /mnt
      
  - name: add user to docker group
    user:
      name: "ubuntu"
      group: "docker"
      append: yes

  - name: Rename The Directory
    command: "mv /mnt/IAC /mnt/Django-Registration_Task"
    
  - name: User Permission
    command: "sudo usermod -aG docker ubuntu"

  - name: Run the Script
    command: "sh /mnt/start_service.sh"
