---
- name: Deploy app on production server
  hosts: all
  become: yes

  tasks:
  - name: Rename The Directory
    command: "rm -rf /mnt/*"
    
  - name: copy app to remote server
    copy:
      src: ../../IAC
      dest: /mnt/
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: Rename The Directory
    command: "mv /mnt/IAC /mnt/Django-Registration_Task"
    
  - name: Install Extra Packages - Snap Docker
    command: "snap install docker"
        
  - name: Install Extra Packages - Docker Compose
    command: "apt install docker-compose"
  
  - name: run docker container
    command: "docker-compose up -d --build"

