---
- name: Deploy app on production server
  hosts: all
  become: yes
  user: root

  tasks:
  - name: Rename The Directory
    command: chdir=/mnt/ rm -rf *
    
  - name: copy app to remote server
    copy:
      src: ../../IAC
      dest: /mnt
      owner: root
      group: root
      mode: 777

  - name: Rename The Directory
    command: "mv /mnt/IAC /mnt/Django-Registration_Task"
    
  - name: User Permission
    command: "sudo usermod -aG docker ubuntu"

  - name: run docker container
    command: chdir=/mnt/Django-Registration_Task/ docker-compose up -d --build

