---
- name: Deploy app on production server
  hosts: all
  become: yes

  tasks:
  - name: copy app to remote server
    copy:
      src: ../Django-Registration_Task
      dest: /mnt/
      owner: ubuntu
      group: ubuntu
      mode: 0644

  - name: create docker image
    command: "docker compose build"

  - name: run docker container
    command: "docker compose up -d"

