---
- name: Install Docker and docker-compose
  hosts: all
  become: yes

  tasks:
  - name: copy app to remote server
    copy:
      src: script.sh
      dest: /mnt
      owner: ubuntu
      group: ubuntu
      mode: 777
      
  - name: Run the Script
    command: "sh /mnt/script.sh"
